version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hajjumrahflow}
      POSTGRES_USER: ${POSTGRES_USER:-hajjuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hajjpass}
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file: ../.env
    depends_on: [db]
    ports: ["8000:8000"]
volumes:
  pgdata: